In [46]:
import pandas as pd
import numpy as np

df = pd.read_csv('lyrics.csv')
df.head()

index             song  year           artist genre  \
0      0        ego-remix  2009  beyonce-knowles   Pop   
1      1     then-tell-me  2009  beyonce-knowles   Pop   
2      2          honesty  2009  beyonce-knowles   Pop   
3      3  you-are-my-rock  2009  beyonce-knowles   Pop   
4      4    black-culture  2009  beyonce-knowles   Pop   

                                              lyrics  
0  Oh baby, how you doing?\nYou know I'm gonna cu...  
1  playin' everything so easy,\nit's like you see...  
2  If you search\nFor tenderness\nIt isn't hard t...  
3  Oh oh oh I, oh oh oh I\n[Verse 1:]\nIf I wrote...  
4  Party the people, the people the party it's po...

In [47]:
df['lyrics'] = df['lyrics'].apply(lambda l: str(l)
                                  .replace('\n', ' ')
                                  .replace('.', ' ')
                                  .replace(',', ' ')
                                  .replace('?', ' ')
                                  .replace('!', ' ')
                                  .lower())
df['word_count'] = df['lyrics'].str.split(' ').str.len()
df = df[df['word_count'] != 1]
df = df[df['genre'] != 'Not Available']

In [59]:
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

tfidfconverter = TfidfVectorizer(max_features=1500, min_df=5, max_df=0.5, stop_words=stopwords.words('english'))
lyrics = df['lyrics']
X = tfidfconverter.fit_transform(lyrics).toarray()

[nltk_data] Downloading package stopwords to /home/swhitt/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [60]:
import time
startTime = time.time()

y = df['genre']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.05, test_size=0.05, random_state=1)

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10, random_state=0)
classifier.fit(X_train, y_train)
acc_score = classifier.score(X_test, y_test)

preds = classifier.predict(X_test)
print(sklearn.metrics.confusion_matrix(y_test, preds))

endTime = time.time()
elapsedTime = endTime - startTime
print("seconds elapsed: " + str(elapsedTime))
print("acc_score: " + str(acc_score))

[[  40    1    0    9    0   10   22    1   91    0  583]
 [   4   11    0   19    0    1   14    1   44    0  283]
 [   1    0    2    2    0    0    3    0   18    0   84]
 [   6    2    0  854    0    1   15    1   90    0  265]
 [   1    0    0    2    0    2    6    0   12    0  130]
 [  12    0    0    4    0   29   10    7   47    0  243]
 [   4    4    1   37    0    5  382    0   44    0  665]
 [   3    1    0   21    0    5    6   11   44    0  155]
 [  31    4    1   96    0   12   40   10  494    0 1368]
 [   1    0    0    7    0    1    7    0   30    2  131]
 [  69   11    4   99    1   17  245    8  488    0 4424]]
seconds elapsed: 2.8990159034729004
acc_score: 0.5219679251587036


In [61]:
import time
startTime = time.time()

y = df['genre']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.05, test_size=0.05, random_state=1)

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
acc_score = classifier.score(X_test, y_test)

preds = classifier.predict(X_test)
print(sklearn.metrics.confusion_matrix(y_test, preds))

endTime = time.time()
elapsedTime = endTime - startTime
print("seconds elapsed: " + str(elapsedTime))
print("acc_score: " + str(acc_score))

[[   0    0    0    2    0    0    6    2    5    0  742]
 [   0    0    0   19    0    0    4    0   12    0  342]
 [   0    0    0    3    0    0    2    0   14    0   91]
 [   0    0    0  772    0    0    0    5   51    0  406]
 [   0    0    0    1    0    0    0    1    5    0  146]
 [   0    0    0    4    0    0    0    2   17    0  329]
 [   0    0    0   39    0    0  345    0   29    0  729]
 [   0    0    0   13    0    0    1    3   57    0  172]
 [   0    0    0   74    0    0    7    4  242    0 1729]
 [   0    0    0    5    0    0    2    0    1    0  171]
 [   2    0    0  103    0    0   72    5  215    0 4969]]
seconds elapsed: 0.7105729579925537
acc_score: 0.5288172402271968
